### ISSUE TITLE
Add generic github auth / remove auth for "OSS mode"

### ISSUE THREAD

**Issue by cowboy** [bocoup/service-catalog#20]
Generic github auth will be done as an example in the react-router-oauth project.

See https://github.com/bocoup/react-router-oauth/issues/1

**Comment by jennschiffer** [comment]
:+1:

**Comment by cowboy** [comment]
I'm going to close this issue, because I'm not sure if it makes sense for this app to have an "OSS" mode when the react-router-oauth module is going to have a github auth example.
