### ISSUE TITLE
perform user interview with lorin / francis on service catalog

### ISSUE THREAD

**Issue by tkellen** [bocoup/service-catalog#3]
The output of this issue should be captured in a section in the project brief:
https://docs.google.com/document/d/1w8Vs7os5CNlPaWx189ZD_mfUL6ROYAuUpuRczenlOIc/edit

**Comment by jennschiffer** [comment]
## Lorin's feedback

* what is this?
* didn't realize that this is the list of our services
* may have been told but there were so many things going on during onboarding
* alphabetical not helpful
* would probably just ask someone for info
* didn't notice search, now understands alphabetical is best
* better descriptions for better search

## post-discussion feedback

* we should highlight search results
* more info link needed, maybe every other part of box on click launches the event
